services:
  # 1. PostgreSQL Database (локальная для Development)
  nest-bot:
    build: .
    container_name: nest_bot
    restart: always
    env_file: .env
    depends_on:
      tg_bot_redis_prod:
        condition: service_started
    volumes:
      - bot_downloads:/tmp/bot_downloads
    ports:
      - '3000:3000'
    networks:
      - bot-network
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 512M
  postgres:
    image: postgres:16-alpine
    container_name: tg_bot_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Redis для очередей BullMQ (Development)
  tg_bot_redis:
    image: redis:7-alpine
    container_name: tg_bot_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly no --save ""
    networks:
      - bot-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

# Описываем тома
volumes:
  postgres_data:
  redis_data:
  bot_downloads:

# Создаем сеть для контейнеров
networks:
  bot-network:
    driver: bridge
