services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: tg_bot_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis для очередей
  redis:
    image: redis:7-alpine
    container_name: tg_bot_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly no --save ""
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # NestJS Application
  nest-bot:
    build: .
    container_name: nest_bot
    restart: always
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./downloads:/app/downloads
    ports:
      - "3000:3000"
    networks:
      - bot-network
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/bot_db
      - DIRECT_URL=postgresql://postgres:postgres@postgres:5432/bot_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379

# Описываем тома
volumes:
  postgres_data:
  redis_data:

# Создаем сеть для контейнеров
networks:
  bot-network:
    driver: bridge
